version: '2'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      # - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
      # - KAFKA_ADVERTISED_PORT=9092
      # - KAFKA_CREATE_TOPICS=customer:1:1,audit:1:1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9999

  kafka-jmx-exporter:
    build: ./jmx_exporter
    ports: 
      - "5556:5556"  
    depends_on:
      - kafka
    # environment:
      # - JMX_PORT=9999
      # - JMX_HOST=kafka
    #   - HTTP_PORT=8080
    #   - JMX_EXPORTER_CONFIG_FILE=./prometheus-jmx-exporter/config.yml

  # prometheus:
  #   ports:
  #     - 9090:9090/tcp
  #   image: prom/prometheus
  #   links:
  #     - kafka-jmx-exporter
  #   volumes:
  #     - ./prometheus-config:/etc/prometheus/
  #   command:
  #     - '-config.file=/etc/prometheus/prometheus.yml'

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000/tcp
  #   links:
  #     - prometheus
  #   environment:
  #     GF_SECURITY_ADMIN_PASSWORD: pass